name: Template Docker Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        description: "Name of the Docker image to be pushed."
        type: string
        required: true
      image_tag:
        description: "Tag for the Docker image to be pushed."
        type: string
        required: true
      context:
        description: "Context of Docker build (e.g., ./)."
        type: string
        required: false
        default: "./"
      dockerfile:
        description: "Relative path to the Dockerfile (e.g., etc/docker/<image_name>/Dockerfile)."
        type: string
        required: true
      platforms:
        description: "Target platforms for the image (e.g., linux/amd64, linux/arm64)."
        type: string
        required: false
        default: "linux/amd64"
      push:
        description: "Whether to push the built image."
        type: boolean
        required: false
        default: true
      registry:
        description: "Docker registry domain to push the image (e.g., ghcr.io)."
        type: string
        required: false
        default: "ghcr.io"
      organization:
        description: "GitHub organization name for the image repository."
        type: string
        required: false
        default: "dyvenia"
      repository_path:
        description: "Repo path under organization, e.g. dyvenia-artifacts"
        type: string
        required: false
      username:
        description: "Username used to GitHub Container Registry login."
        type: string
        required: false
        default: ${{ github.actor }}
      build-args:
        description: "Set build-time variables for Dockerfile."
        type: string
        required: false
      target:
        description: "Optional build stage name from the Dockerfile."
        type: string
        required: false
    secrets:
      token:
        description: "Authentication token for logging into the GitHub Container Registry. Typically, this should be set to secrets.GITHUB_TOKEN passed from the calling workflow."
        required: true

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}

      - name: "Build and Push Docker Image"
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.registry }}/${{ inputs.organization }}${{ inputs.repository_path }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
          build-args: ${{ inputs.build-args }}
          target: ${{ inputs.target }}
